/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccaRouteImport } from './routes/acca'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AccaCodeRouteImport } from './routes/acca.$code'
import { Route as AccaPublicRouteImport } from './routes/acca.public'
import { Route as LeaguesIndexRouteImport } from './routes/leagues.index'
import { Route as LeaguesLeagueIdRouteImport } from './routes/leagues.$leagueId'
import { Route as MatchesIndexRouteImport } from './routes/matches.index'
import { Route as MatchesEventIdRouteImport } from './routes/matches.$eventId'
import { Route as PlayersPlayerIdRouteImport } from './routes/players.$playerId'
import { Route as PredictionsIndexRouteImport } from './routes/predictions.index'
import { Route as TeamsTeamIdRouteImport } from './routes/teams.$teamId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccaRoute = AccaRouteImport.update({
  id: '/acca',
  path: '/acca',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AccaCodeRoute = AccaCodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => AccaRoute,
} as any)
const AccaPublicRoute = AccaPublicRouteImport.update({
  id: '/public',
  path: '/public',
  getParentRoute: () => AccaRoute,
} as any)
const LeaguesIndexRoute = LeaguesIndexRouteImport.update({
  id: '/leagues/',
  path: '/leagues/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaguesLeagueIdRoute = LeaguesLeagueIdRouteImport.update({
  id: '/leagues/$leagueId',
  path: '/leagues/$leagueId',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesIndexRoute = MatchesIndexRouteImport.update({
  id: '/matches/',
  path: '/matches/',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesEventIdRoute = MatchesEventIdRouteImport.update({
  id: '/matches/$eventId',
  path: '/matches/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersPlayerIdRoute = PlayersPlayerIdRouteImport.update({
  id: '/players/$playerId',
  path: '/players/$playerId',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictionsIndexRoute = PredictionsIndexRouteImport.update({
  id: '/predictions/',
  path: '/predictions/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsTeamIdRoute = TeamsTeamIdRouteImport.update({
  id: '/teams/$teamId',
  path: '/teams/$teamId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acca': typeof AccaRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/acca/$code': typeof AccaCodeRoute
  '/acca/public': typeof AccaPublicRoute
  '/leagues/$leagueId': typeof LeaguesLeagueIdRoute
  '/matches/$eventId': typeof MatchesEventIdRoute
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/leagues/': typeof LeaguesIndexRoute
  '/matches/': typeof MatchesIndexRoute
  '/predictions/': typeof PredictionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acca': typeof AccaRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/acca/$code': typeof AccaCodeRoute
  '/acca/public': typeof AccaPublicRoute
  '/leagues/$leagueId': typeof LeaguesLeagueIdRoute
  '/matches/$eventId': typeof MatchesEventIdRoute
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/leagues': typeof LeaguesIndexRoute
  '/matches': typeof MatchesIndexRoute
  '/predictions': typeof PredictionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acca': typeof AccaRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/acca/$code': typeof AccaCodeRoute
  '/acca/public': typeof AccaPublicRoute
  '/leagues/$leagueId': typeof LeaguesLeagueIdRoute
  '/matches/$eventId': typeof MatchesEventIdRoute
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/leagues/': typeof LeaguesIndexRoute
  '/matches/': typeof MatchesIndexRoute
  '/predictions/': typeof PredictionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acca'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/acca/$code'
    | '/acca/public'
    | '/leagues/$leagueId'
    | '/matches/$eventId'
    | '/players/$playerId'
    | '/teams/$teamId'
    | '/leagues/'
    | '/matches/'
    | '/predictions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acca'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/acca/$code'
    | '/acca/public'
    | '/leagues/$leagueId'
    | '/matches/$eventId'
    | '/players/$playerId'
    | '/teams/$teamId'
    | '/leagues'
    | '/matches'
    | '/predictions'
  id:
    | '__root__'
    | '/'
    | '/acca'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/acca/$code'
    | '/acca/public'
    | '/leagues/$leagueId'
    | '/matches/$eventId'
    | '/players/$playerId'
    | '/teams/$teamId'
    | '/leagues/'
    | '/matches/'
    | '/predictions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccaRoute: typeof AccaRouteWithChildren
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  LeaguesLeagueIdRoute: typeof LeaguesLeagueIdRoute
  MatchesEventIdRoute: typeof MatchesEventIdRoute
  PlayersPlayerIdRoute: typeof PlayersPlayerIdRoute
  TeamsTeamIdRoute: typeof TeamsTeamIdRoute
  LeaguesIndexRoute: typeof LeaguesIndexRoute
  MatchesIndexRoute: typeof MatchesIndexRoute
  PredictionsIndexRoute: typeof PredictionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acca': {
      id: '/acca'
      path: '/acca'
      fullPath: '/acca'
      preLoaderRoute: typeof AccaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acca/$code': {
      id: '/acca/$code'
      path: '/$code'
      fullPath: '/acca/$code'
      preLoaderRoute: typeof AccaCodeRouteImport
      parentRoute: typeof AccaRoute
    }
    '/acca/public': {
      id: '/acca/public'
      path: '/public'
      fullPath: '/acca/public'
      preLoaderRoute: typeof AccaPublicRouteImport
      parentRoute: typeof AccaRoute
    }
    '/leagues/': {
      id: '/leagues/'
      path: '/leagues'
      fullPath: '/leagues/'
      preLoaderRoute: typeof LeaguesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leagues/$leagueId': {
      id: '/leagues/$leagueId'
      path: '/leagues/$leagueId'
      fullPath: '/leagues/$leagueId'
      preLoaderRoute: typeof LeaguesLeagueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/': {
      id: '/matches/'
      path: '/matches'
      fullPath: '/matches/'
      preLoaderRoute: typeof MatchesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/$eventId': {
      id: '/matches/$eventId'
      path: '/matches/$eventId'
      fullPath: '/matches/$eventId'
      preLoaderRoute: typeof MatchesEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/$playerId': {
      id: '/players/$playerId'
      path: '/players/$playerId'
      fullPath: '/players/$playerId'
      preLoaderRoute: typeof PlayersPlayerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predictions/': {
      id: '/predictions/'
      path: '/predictions'
      fullPath: '/predictions/'
      preLoaderRoute: typeof PredictionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamId': {
      id: '/teams/$teamId'
      path: '/teams/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof TeamsTeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AccaRouteChildren {
  AccaCodeRoute: typeof AccaCodeRoute
  AccaPublicRoute: typeof AccaPublicRoute
}

const AccaRouteChildren: AccaRouteChildren = {
  AccaCodeRoute: AccaCodeRoute,
  AccaPublicRoute: AccaPublicRoute,
}

const AccaRouteWithChildren = AccaRoute._addFileChildren(AccaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccaRoute: AccaRouteWithChildren,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  LeaguesLeagueIdRoute: LeaguesLeagueIdRoute,
  MatchesEventIdRoute: MatchesEventIdRoute,
  PlayersPlayerIdRoute: PlayersPlayerIdRoute,
  TeamsTeamIdRoute: TeamsTeamIdRoute,
  LeaguesIndexRoute: LeaguesIndexRoute,
  MatchesIndexRoute: MatchesIndexRoute,
  PredictionsIndexRoute: PredictionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
